"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['SKIP', 'STOP', 'Op', 'Map', 'Filter', 'Limit', 'Select', 'GroupBy', 'Reduce', 'Sort', 'Condition', 'F', 'read_csv',
           'read_sqlite3', 'Query', 'GroupedQuery']

# %% ../nbs/00_core.ipynb #0be2a17d
import csv
import sqlite3

# %% ../nbs/00_core.ipynb #11ccdbfc
SKIP = object()
STOP = object()

# %% ../nbs/00_core.ipynb #e805af66
class Op:
    def __init__(self, factory, name):
        self.name = name
        self.factory = factory
    def __call__(self): return self.factory()

# %% ../nbs/00_core.ipynb #f232b628
class Map:
    def __init__(self, fn): self.fn = fn
    def __call__(self, item): return self.fn(item)

class Filter:
    def __init__(self, fn): self.fn = fn
    def __call__(self, item):
        if not self.fn(item): return SKIP
        return item

class Limit:
    def __init__(self, n):
        self.n = n
        self.count = 0
    def __call__(self, item):
        if self.count >= self.n: return STOP
        self.count += 1
        return item

class Select:
    def __init__(self, keys): self.keys = keys if isinstance(keys, list) else [keys]
    def __call__(self, item): return {k: item[k] for k in self.keys}

class GroupBy:
    def __init__(self, key): self.key = key
    def run(self, data):
        groups = {}
        for item in data:
            k = item[self.key]
            if k not in groups: groups[k] = []
            groups[k].append(item)
        return groups.items()

class Reduce:
    def __init__(self, fn, initial=None):
        self.fn = fn
        self.initial = initial
    def run(self, data):
        it = iter(data)
        if self.initial is None:
            try: acc = next(it)
            except StopIteration: return []
        else: acc = self.initial
        for item in it: acc = self.fn(acc, item)
        return [acc]

class Sort:
    def __init__(self, key, reverse=False):
        self.key = key
        self.reverse = reverse
    def run(self, data):
        return sorted(data, key=lambda item: item[self.key] if isinstance(item, dict) else item[self.key], reverse=self.reverse)


# %% ../nbs/00_core.ipynb #abd3d4b6
class Condition:
    def __init__(self, fn): self.fn = fn
    def __call__(self, x): return self.fn(x)
    def __and__(self, other): return Condition(lambda x: self(x) and other(x))

class F:
    def __init__(self, name): self.name = name
    def __eq__(self, value): return Condition(lambda x: x[self.name] == value)
    def __gt__(self, value): return Condition(lambda x: x[self.name] > value)
    def __lt__(self, value): return Condition(lambda x: x[self.name] < value)
    def not_null(self): return Condition(lambda x: x.get(self.name) is not None)
    def is_null(self): return Condition(lambda x: x.get(self.name) is None)


# %% ../nbs/00_core.ipynb #a10f1e4f
def read_csv(path):
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader: yield row

def read_sqlite3(db_path, query):
    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()
        cursor.execute(query)
        cols = [col[0] for col in cursor.description]
        for row in cursor: yield dict(zip(cols, row))


# %% ../nbs/00_core.ipynb #e1079d3a
class Query:
    def __init__(self, data, operations=None):
        self.data = data
        self.operations = operations or []
    def map(self, fn): return Query(self.data, self.operations + [Op(lambda: Map(fn), 'map')])
    def filter(self, fn): return Query(self.data, self.operations + [Op(lambda: Filter(fn), 'filter')])
    def limit(self, n): return Query(self.data, self.operations + [Op(lambda: Limit(n), f'limit({n})')])
    def select(self, keys): return Query(self.data, self.operations + [Op(lambda: Select(keys), f'select({keys})')])
    def groupby(self, key): return GroupedQuery(self.data, self.operations + [Op(lambda: GroupBy(key), f'groupby({key})')])
    def reduce(self, fn, initial=None): return Query(self.data, self.operations + [Op(lambda: Reduce(fn, initial), 'reduce')])
    def sort(self, key, reverse=False):
        name = f'sort({key}, desc)' if reverse else f'sort({key})'
        return Query(self.data, self.operations + [Op(lambda: Sort(key, reverse), name)])
    def sum(self): return Query(self.data, self.operations + [Op(lambda: Reduce(lambda acc, x: acc + x), 'sum')])
    def count(self): return Query(self.data, self.operations + [Op(lambda: Reduce(lambda acc, _: acc + 1, 0), 'count')])
    def min(self): return Query(self.data, self.operations + [Op(lambda: Reduce(lambda acc, x: x if x < acc else acc), 'min')])
    def max(self): return Query(self.data, self.operations + [Op(lambda: Reduce(lambda acc, x: x if x > acc else acc), 'max')])

    def __repr__(self):
        if not self.operations: return f"{self.__class__.__name__}()"
        return f"{self.__class__.__name__}(" + " -> ".join(op.name for op in self.operations) + ")"

    def __iter__(self):
        ops = [op() for op in self.operations]
        data = self.data() if callable(self.data) else self.data
        for op in ops:
            if isinstance(op, (GroupBy, Reduce, Sort)): data = op.run(data)
            else: data = self._apply_stream_op(data, op)
        for item in data: yield item

    def _apply_stream_op(self, data, op):
        for item in data:
            item = op(item)
            if item is STOP: return
            if item is SKIP: continue
            yield item

    def collect(self, n=None): return list(self) if n is None else list(self)[:n]
    def show(self, n=5):
        for i, item in enumerate(self):
            if i == n: break
            print(item)

    @classmethod
    def from_iterable(cls, data): return cls(data)
    @classmethod
    def from_csv(cls, path): return cls(lambda: read_csv(path))
    @classmethod
    def from_sqlite(cls, db_path, table): return cls(lambda: read_sqlite3(db_path, f'SELECT * FROM {table}'))
    @classmethod
    def from_sqlite_query(cls, db_path, query): return cls(lambda: read_sqlite3(db_path, query))

class GroupedQuery(Query):
    def __init__(self, data, operations=None): super().__init__(data, operations)
    def count(self): return Query(self.data, self.operations + [Op(lambda: Map(lambda g: (g[0], len(g[1]))), 'count')])
    def sum(self, field): return Query(self.data, self.operations + [Op(lambda: Map(lambda g: (g[0], sum(int(i[field]) for i in g[1]))), 'sum')])
    def take(self, n): return GroupedQuery(self.data, self.operations + [Op(lambda: Map(lambda g: (g[0], g[1][:n])), f"take({n})")])
    def map(self, fn): return GroupedQuery(self.data, self.operations + [Op(lambda: Map(fn), 'map')])

